const MUSHROOMS = [
    "Unknown",
    "Other",
    "Alder Scalycap",
    "American slippery Jack",
    "Apple Webcap",
    "Arched Wood Wax",
    "Bay Bolete",
    "Bay Cup",
    "Bear's head",
    "Birch Milkcap",
    "Bitter Bolete",
    "Bitter Oak-Stump Mushroom",
    "Bitter Yellow Knight",
    "Black Morel",
    "Blushing Amanita",
    "Blushing Flagrant Tooth",
    "Booted Knight",
    "Brick Tuft",
    "Broad-gilled Collybia",
    "Brown Birch Bolete",
    "Brown Mottlegill",
    "Caged stinkhorn",
    "Chicken of the Woods",
    "Cinnabar Powdercap",
    "Club Foot",
    "Collared Parachute",
    "Collared mosscap",
    "Common Chantarelle",
    "Common Funnel Cap",
    "Common Ink Cap",
    "Common Laccaria",
    "Common Morel",
    "Common Park Psathyrella",
    "Common Puffball",
    "Common Tufted Mycena",
    "Conifer Roundhead",
    "Conifer Tuft",
    "Conifer Woodtuft",
    "Copper Brittlegill",
    "Coral Brittlegill",
    "Coral fungi",
    "Cow mushroom",
    "Crab Russula",
    "Curry Milkcap",
    "Cursed Webcap",
    "Cystoderma amianthinum",
    "Cystodermella cinnabarina",
    "Deadly Webcap",
    "Deceiving Knight",
    "Devil’s Stinkhorn",
    "Dry Scaly Pholiota",
    "Dryad’s Saddle",
    "Dusky Puffball",
    "Earthy Powdercap",
    "Eastern jack-o'lantern",
    "Elastic Saddle",
    "Entoloma sericeum",
    "Fairy Inkcap",
    "Fairy Ring Marasmius",
    "False Chanterelle",
    "False Morel",
    "Flowerpot parasol",
    "Fool's Webcap",
    "Fringed Polypore",
    "Funeral Bell",
    "Funnel Cap",
    "Fused Polypore",
    "Gassy webcap",
    "Giant puffball",
    "Goatcheese webcap",
    "Golden Scalycap",
    "Golden oyster mushroom",
    "Gomphidius glutinosus",
    "Grainy Wax Cap",
    "Green Brittlegill",
    "Grey veiled amanita",
    "Grisette",
    "Gypsy Mushroom",
    "Hedgehog Mushroom",
    "Honey Mushroom",
    "Hooded false morel",
    "Hot Russula",
    "Hygrophorus camarophyllus",
    "Hygrophorus hypothejus",
    "Hygrophorus pustulatus",
    "Indian Oyster",
    "Indigo Milkcap",
    "Jelly Baby",
    "Larch Bolete",
    "Late Fall Wax Cap",
    "Lemon-Peel Cup",
    "Lemon-yellow Pholiota",
    "Liberty Cap",
    "Lion's mane",
    "Luscious Lactarius",
    "Lycoperdon excipuliforme",
    "Lycoperdon nigrescens",
    "Lycoperdon perlatum",
    "Lycoperdon pratense",
    "Lycoperdon pyriforme",
    "Macrolepiota procera",
    "Meadow Mushroom",
    "Meadow Puffball",
    "Milkcap",
    "Milky Conecap",
    "Mycena epipterygia",
    "Mycena galericulata",
    "Mycena laevigata",
    "Mycena pura",
    "Old Man of the Woods",
    "Orange Birch Bolete",
    "Orange Milkcap",
    "Orange Oak Bolete",
    "Orange Peel Fungus",
    "Oyster Rollrim",
    "Oyster mushroom",
    "Paltry Puffball",
    "Parasol Mushroom",
    "Peppery Bolete",
    "Peppery Milkcap",
    "Pine Cone Cap",
    "Pine firefungus",
    "Pink Lawn Trich",
    "Pinkgill mushroom",
    "Pistle-shaped Puffball",
    "Plums and Custard",
    "Poison Lactarius",
    "Poison Pax",
    "Poison Radish Ground Mycena",
    "Poison Webcap",
    "Prunes and Custard",
    "Red cracking bolete",
    "Red-Capped Scaber Stalk",
    "Red-banded Cort",
    "Rough-stemmed bolete",
    "Ruby Bolete",
    "Rufous Milkcap",
    "Russula claroflava",
    "Russula velenovskyi",
    "Rusty Gilled polypore",
    "Saffron Milkcap",
    "Saffron Webcap",
    "Scaly Chanterelle",
    "Scaly Tooth",
    "Scaly Webcap",
    "Shaggy Parasol",
    "Shaggy-mane Inky Cap",
    "Sheathed Woodtuft",
    "Shield Dapperling",
    "Silky Pinkgill",
    "Silvery Violet Cort",
    "Slimy Lead Lactarius",
    "Slimy Spike",
    "Slimy Tuft",
    "Smoky Webcap",
    "Smooth Mycena",
    "Snakeskin Brownie",
    "Soapy Knight",
    "Spring Cavalier",
    "Spruce Cone Cap",
    "St George's Mushroom",
    "Stinkhorn",
    "Stinking Parachute",
    "Stump Puffball",
    "Sulphur Tuft",
    "Sunburst Lichen",
    "Terracotta Hedgehog",
    "The Flirt",
    "The Sickener",
    "The Vomiter",
    "Tiered Tooth",
    "Torn Fibrecap",
    "Trumpet Chantarelle",
    "Ugly Milkcap",
    "Umbrella Inky Cap",
    "Variegated Bolete",
    "Velvet Milkcap",
    "Velvet Rollrim",
    "Violet Cort",
    "Weeping Widow",
    "White Domecap",
    "Winecork Brittlegill",
    "Wood Blewit",
    "Wood Mushroom",
    "Wood Woollyfoot",
    "Woolly Milkcap",
    "Woolly Webcap",
    "Yellow Knight",
    "Yellow Swamp Brittlegill",
    "Yellowleg Bonnet"
];

export default MUSHROOMS;
